### PR TITLE
Fixes #3 updates golang & alpine

### LINKED ISSUE #3: Update Docker build layer to go 1.11.13
Per the security announcement https://groups.google.com/forum/#!topic/golang-announce/65QixT3tcmg we should update the docker build layers to at least Go 1.11.13

## Possible Solution

The builder layer in the Dockerfile should use `golang:1.11`

### Update Dockerfile and rebuild/release
https://github.com/openfaas/faas/issues/1291
https://github.com/openfaas/templates/issues/170
https://github.com/openfaas/faas-netes/issues/494
https://github.com/openfaas/nats-queue-worker/issues/66
https://github.com/openfaas-incubator/of-watchdog/issues/78
https://github.com/openfaas-incubator/faas-idler/issues/32
https://github.com/openfaas-incubator/golang-http-template/issues/28
https://github.com/openfaas-incubator/faas-federation/issues/4
https://github.com/openfaas-incubator/vcenter-connector/issues/27
https://github.com/openfaas-incubator/faas-memory/issues/3
https://github.com/openfaas-incubator/faas-rancher/issues/8

### Only Rebuild
https://github.com/openfaas/faas-swarm/issues/56
https://github.com/openfaas-incubator/ingress-operator/issues/10
https://github.com/openfaas-incubator/openfaas-operator/issues/87

### PR DESCRIPTION
**Pull request by ewilde**
Signed-off-by: Edward Wilde <ewilde@gmail.com>

### CODE REVIEW

**Comment by alexellis** [comment]
Please add:

```
ENV CGO_ENABLED=0
```

**Comment by alexellis** [comment]
Did `make` / `docker build` pass?

**Comment by ewilde** [comment]
> Did `make` / `docker build` pass?

yes it builds the image

**Comment by alexellis** [comment]
Please add the requested when you can

**Comment by ewilde** [comment]
> Please add the requested when you can

Please see: https://github.com/openfaas-incubator/faas-memory/pull/5

**Pull request merged**
